### ISSUE TITLE
Bluetooth gets disabled everytime i resume after suspend

### ISSUE THREAD

**Issue by arnavgr** [Fasolovic/hyprland-suspend-fix#2]
First of all, thank you for this amazing script it is a lifesaver

i have my bluetoooth keyboard connected to my pc but evertime i wake up after suspend my bluetooth service gets disabled with this log

 bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; preset: disabled)
     Active: failed (Result: core-dump) since Fri 2024-04-19 17:58:32 IST; 15s ago
   Duration: 22.090s
       Docs: man:bluetoothd(8)
    Process: 18038 ExecStart=/usr/lib/bluetooth/bluetoothd (code=dumped, signal=ABRT)
   Main PID: 18038 (code=dumped, signal=ABRT)
     Status: "Running"
        CPU: 200ms

Apr 19 17:58:23 arch bluetoothd[18038]: Endpoint unregistered: sender=:1.173 path=/MediaEndpoint/A2DPS>
Apr 19 17:58:23 arch bluetoothd[18038]: Endpoint unregistered: sender=:1.173 path=/MediaEndpoint/A2DPS>
Apr 19 17:58:23 arch bluetoothd[18038]: Endpoint unregistered: sender=:1.173 path=/MediaEndpoint/A2DPS>
Apr 19 17:58:23 arch bluetoothd[18038]: Endpoint unregistered: sender=:1.173 path=/MediaEndpoint/A2DPS>
Apr 19 17:58:23 arch bluetoothd[18038]: Endpoint unregistered: sender=:1.173 path=/MediaEndpoint/A2DPS>
Apr 19 17:58:23 arch bluetoothd[18038]: Endpoint unregistered: sender=:1.173 path=/MediaEndpoint/A2DPS>
Apr 19 17:58:30 arch bluetoothd[18038]: profiles/input/device.c:hidp_send_message() BT socket not conn>
Apr 19 17:58:31 arch bluetoothd[18038]: free(): invalid pointer
Apr 19 17:58:32 arch systemd[1]: bluetooth.service: Main process exited, code=dumped, status=6/ABRT
Apr 19 17:58:32 arch systemd[1]: bluetooth.service: Failed with result 'core-dump'.

how do i fix this?
~

**Comment by arnavgr** [comment]
not a problem caused by this script

its a bluez problem

**Comment by 0xFMD** [comment]
@arnavgr Glad to hear that. Sorry for not responding; I've been busy with ongoing exams and university stuff

**Comment by arnavgr** [comment]
> @arnavgr Glad to hear that. Sorry for not responding; I've been busy with ongoing exams and university stuff

Please take a look at my PR, thank you for your time
